-- Delete all existing addon services
DELETE FROM addon_services;

-- Reset auto increment
ALTER TABLE addon_services AUTO_INCREMENT = 1;

-- Insert all 78 services from Satkhira Decorator Association price list
-- সাতক্ষীরা জেলা ডেকোরেটর মালিক সমিতি
INSERT INTO addon_services (name, description, category, price, isActive) VALUES
-- Services 01-39 (Left Column)
('চেয়ার প্লাস্টিক', '১টি', 'decoration', 5, true),
('চেয়ার প্লাস্টিক (হাতল)', '১টি', 'decoration', 10, true),
('চেয়ার (ভি.আই.পি কুশন)', '১টি', 'decoration', 100, true),
('চেয়ার কভার', '১টি', 'decoration', 15, true),
('হাড়ি বা ডেকচি ২৬ পর্যন্ত', '১টি', 'catering', 25, true),
('হাড়ি বা ডেকচি ২৮/৩০', '১টি', 'catering', 150, true),
('কড়াই ছোট', '১টি', 'catering', 25, true),
('কড়াই লোহার', '১টি', 'catering', 200, true),
('গন', '১টি', 'catering', 100, true),
('হামান দিস্তা', '১টি', 'catering', 25, true),
('কিমা মেশিন', '১টি', 'catering', 250, true),
('ওয়াশিং পট', '১টি', 'catering', 75, true),
('গামলা স্টীল', '১টি', 'catering', 75, true),
('গামলা ম্যালামাইন', '১টি', 'catering', 15, true),
('জগ প্লাস্টিক', '১টি', 'catering', 30, true),
('জগ কাঁচ', '১টি', 'catering', 20, true),
('ম্যালামাইন প্লেট', '১টি', 'catering', 5, true),
('কড়ির প্লেট', '১টি', 'catering', 10, true),
('প্লেট হাফ কড়ি', '১টি', 'catering', 5, true),
('গ্লাস ম্যালামাইন', '১টি', 'catering', 5, true),
('গ্লাস কাঁচের', '১টি', 'catering', 5, true),
('রাইস ডিস ম্যালামাইন', '১টি', 'catering', 20, true),
('চামচ স্টীল', '১টি', 'catering', 5, true),
('চা অথবা কাটা চামচ', '১টি', 'catering', 0, true),
('পানির ড্রাম', '১টি', 'catering', 300, true),
('বেসিন ডাবল', '১টি', 'other', 500, true),
('বেসিন সিংগেল', '১টি', 'other', 300, true),
('বরের প্লেট', '১টি', 'decoration', 200, true),
('সুপ বাটি', '১টি', 'catering', 30, true),
('বালতি', '১টি', 'other', 50, true),
('টেবিল লম্বা', '১টি', 'decoration', 50, true),
('টেবিল গোল', '১টি', 'decoration', 100, true),
('টেবিল ক্লথ', '১টি', 'decoration', 20, true),
('টেবিল স্কেটিং', '১ জোড়া', 'decoration', 800, true),
('টেবিল স্কেটিং সিংগেল', '১টি', 'decoration', 200, true),
('সামিয়ানা ১৫ × ২০ ফুট', '১টি', 'decoration', 3000, true),
('চেন টু কালার', 'প্রতি সেট', 'decoration', 50, true),
('চেন এক কালার', 'প্রতি সেট', 'decoration', 100, true),
('বড় পতাকা পাইপ ফিটিং সহ', '১টি', 'decoration', 500, true),

-- Services 40-78 (Right Column)
('শো পতাকা পাইপ ফিটিংস', '১টি', 'decoration', 50, true),
('ডাবল', '১টি', 'decoration', 80, true),
('বিস্কো ১০ x ৫০ ফুট', '১টি', 'decoration', 200, true),
('বিস্কো ১০ x ৩০ ফুট', '১টি', 'decoration', 800, true),
('বিস্কো ১০ x ২০ ফুট', '১টি', 'decoration', 600, true),
('জেনারেটর', '১টি', 'other', 1000, true),
('প্যান্ডেল মাটিতে সাধারণ', 'স্কয়ার ফুট', 'decoration', 5, true),
('প্যান্ডেল ওয়াটারপ্রুফ মাটিতে', 'স্কয়ার ফুট', 'decoration', 10, true),
('প্যান্ডেল সাধারণ ছাদে ১ম তলা', 'স্কয়ার ফুট', 'decoration', 8, true),
('প্যান্ডেল ওয়াটারপ্রুফ ছাদে', 'স্কয়ার ফুট', 'decoration', 15, true),
('ভিআইপি প্যান্ডেল', 'স্কয়ার ফুট', 'decoration', 15, true),
('গেইট মাঝারি', '১টি', 'decoration', 3500, true),
('গেট কর্কেট কুচি', '১টি', 'decoration', 5000, true),
('গেট ড্রাম', '১টি', 'decoration', 1000, true),
('গেট সিংগেল রোড ক্রস হাইওয়ে', '১টি', 'decoration', 30000, true),
('গেট ডাবল রোড ক্রস হাইওয়ে', '১টি', 'decoration', 15000, true),
('জুট ম্যাট ৩০ ফুট', '১টি', 'decoration', 200, true),
('রেড কার্পেট ৩০ x ৪ ফুট', '১টি', 'decoration', 800, true),
('রেড কার্পেট ৮/৩০ ফুট', '১টি', 'decoration', 600, true),
('বর / বউ / হলুদ আসন ২ টেবিলের', '১টি', 'decoration', 8000, true),
('রান্নর ছাউনি ত্রিপল ২০-৩০ ফুট', '১টি', 'decoration', 2000, true),
('ফ্যান স্ট্যান', '১টি', 'other', 600, true),
('টিউব লাইট', '১টি', 'decoration', 50, true),
('হ্যালোজেন লাইট', '১টি', 'decoration', 100, true),
('লাইটিং গেট প্রতি পার্ট', '১টি', 'decoration', 500, true),
('বসার ত্রিপল ২০ x ৩০ ফুট', '১টি', 'decoration', 300, true),
('রোড সিনারি বোর্ড', '১টি', 'decoration', 300, true),
('চট বসার ২/২০ হাত', '১টি', 'decoration', 100, true),
('পিতলের ফুলের টব', '১টি', 'decoration', 200, true),
('স্পিচ ডায়াস (কাঠের)', '১টি', 'decoration', 300, true),
('স্পিচ ডায়াস (স্টীলের)', '১টি', 'decoration', 500, true),
('সোফা প্রতি ১ সিটের স্টিল', '১টি', 'decoration', 300, true),
('পার্কার লাইট প্রতি পিস', '১টি', 'decoration', 200, true),
('স্টেজ উচ্চতা ১.৫ ফুট', 'প্রতি টেবিল', 'decoration', 500, true),
('স্টেজ উচ্চতা ২.৫ ফুট', 'প্রতি টেবিল', 'decoration', 500, true),
('স্টেজ উচ্চতা ৫ ফুট', 'প্রতি টেবিল', 'decoration', 1000, true),
('সোফা দুই সিটের ডিমান্ড', '১টি', 'decoration', 1500, true),
('সোফা ৩ সিটের ডিমান্ড', '১টি', 'decoration', 2000, true),
('সেলুটিং ডায়াস ৩ টেবিলের', '১টি', 'decoration', 5000, true);

-- Show inserted count
SELECT COUNT(*) as total_services FROM addon_services;
